# application.yml
server:
  port: 8080
spring:
  profiles:
    active: secret  # ✅ 이걸로 secret 설정 불러옴

  datasource:
    url: jdbc:postgresql://localhost:5432/BlogPostgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
