import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import localFont from 'next/font/local';
import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

const bmjua = localFont({
  src: '../../public/font/BMJUA.ttf',
  variable: '--font-bmjua',
});

export const metadata: Metadata = {
  title: 'emotion blog',
  description: 'Generated by create next app',
  icons: {
    icon: '/favicon.svg',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} ${bmjua.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
